# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Alan/Documents/GitHub/Tempest/tempest/tempest.srcs/sources_1/ip/ROM7/ROM7.xci
# IP: The module: 'ROM7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alan/Documents/GitHub/Tempest/tempest/tempest.srcs/sources_1/ip/ROM7/ROM7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Alan/Documents/GitHub/Tempest/tempest/tempest.srcs/sources_1/ip/ROM7/ROM7.xci
# IP: The module: 'ROM7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alan/Documents/GitHub/Tempest/tempest/tempest.srcs/sources_1/ip/ROM7/ROM7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
