# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/TEMPEST/est/project_1/Nexys-A7-100T-Master.xdc

# IP: ip/vgRAM/vgRAM.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgRAM || ORIG_REF_NAME==vgRAM} -quiet] -quiet

# IP: ip/RAM/RAM.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet
