# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/TEMPEST/est/project_1/Nexys-A7-100T-Master.xdc

# IP: ip/ROM132/ROM132.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM132 || ORIG_REF_NAME==ROM132} -quiet] -quiet

# IP: ip/ROM131/ROM131.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM131 || ORIG_REF_NAME==ROM131} -quiet] -quiet

# IP: ip/ROM130/ROM130.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM130 || ORIG_REF_NAME==ROM130} -quiet] -quiet

# IP: ip/ROM129/ROM129.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM129 || ORIG_REF_NAME==ROM129} -quiet] -quiet

# IP: ip/ROM128/ROM128.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM128 || ORIG_REF_NAME==ROM128} -quiet] -quiet

# IP: ip/ROM127/ROM127.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM127 || ORIG_REF_NAME==ROM127} -quiet] -quiet

# IP: ip/vgROM/vgROM.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgROM || ORIG_REF_NAME==vgROM} -quiet] -quiet

# IP: ip/vgRAM/vgRAM.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vgRAM || ORIG_REF_NAME==vgRAM} -quiet] -quiet

# IP: ip/CombinedROM/CombinedROM.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CombinedROM || ORIG_REF_NAME==CombinedROM} -quiet] -quiet

# IP: ip/ROMX/ROMX.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROMX || ORIG_REF_NAME==ROMX} -quiet] -quiet

# IP: ip/ROM7/ROM7.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM7 || ORIG_REF_NAME==ROM7} -quiet] -quiet

# IP: ip/ROM5/ROM5.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM5 || ORIG_REF_NAME==ROM5} -quiet] -quiet

# IP: ip/ROM3/ROM3.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM3 || ORIG_REF_NAME==ROM3} -quiet] -quiet

# IP: ip/ROM1/ROM1.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM1 || ORIG_REF_NAME==ROM1} -quiet] -quiet

# IP: ip/RAM/RAM.xco
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet
